apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml
  - validation-cronjob.yaml
  - scripts-configmap.yaml
  - config.yaml
  - secrets.yaml

images:
  - name: POSTGRES_IMAGE_PLACEHOLDER
    newName: postgres
    newTag: "17"
