apiVersion: v1
kind: Secret
metadata:
  name: pg-backup-secrets
type: Opaque
stringData:
  # PostgreSQL connection secrets
  pg_username: your_pg_user
  pg_password: your_pg_password
  
  # AWS credentials
  aws_access_key_id: YOUR_KEY
  aws_secret_access_key: YOUR_SECRET
  
  # Backup encryption secret
  encrypt_password: your-strong-password