apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgsql-backup-validation
spec:
  schedule: "30 3 * * *" # Run daily at 3:30 AM, after backup (2:00 AM)
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: validation
              image: POSTGRES_IMAGE_PLACEHOLDER # Kustomize will patch this per environment
              env:
                # Database connection
                - name: PGHOST
                  valueFrom:
                    configMapKeyRef:
                      name: pg-backup-configs
                      key: PG_HOST
                - name: PGDATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: pg-backup-configs
                      key: PG_DATABASE
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: pg-backup-secrets
                      key: pg_username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pg-backup-secrets
                      key: pg_password

                # AWS credentials
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: pg-backup-secrets
                      key: aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: pg-backup-secrets
                      key: aws_secret_access_key

                # Backup parameters
                - name: BACKUP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pg-backup-secrets
                      key: encrypt_password
                - name: S3_BUCKET_PATH
                  valueFrom:
                    configMapKeyRef:
                      name: pg-backup-configs
                      key: S3_BUCKET_PATH

                # Monitoring
                - name: PUSHGATEWAY_URL
                  valueFrom:
                    configMapKeyRef:
                      name: pg-backup-configs
                      key: PUSHGATEWAY_URL

                # Environment configuration
                - name: ENVIRONMENT
                  valueFrom:
                    configMapKeyRef:
                      name: pg-backup-configs
                      key: ENVIRONMENT
                - name: MAX_RETRIES
                  valueFrom:
                    configMapKeyRef:
                      name: pg-backup-configs
                      key: MAX_RETRIES
                - name: RETRY_WAIT
                  valueFrom:
                    configMapKeyRef:
                      name: pg-backup-configs
                      key: RETRY_WAIT
                - name: ENABLE_DEBUG
                  valueFrom:
                    configMapKeyRef:
                      name: pg-backup-configs
                      key: ENABLE_DEBUG
              command:
                - /bin/bash
                - /scripts/validate.sh
              volumeMounts:
                - name: backup-scripts
                  mountPath: /scripts
                  readOnly: true
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
          volumes:
            - name: backup-scripts
              configMap:
                name: pg-backup-scripts
                defaultMode: 0755
