apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - path: secrets.yaml
  - path: configs.yaml
  - path: schedule-patch.yaml

images:
  - name: POSTGRES_IMAGE_PLACEHOLDER
    newName: postgres
    newTag: "17"